version: '3'
services:
   mysql:
     container_name: mysql
     image: mysql:5.7
     ports:
       - 3307:3306
     environment:
       - MYSQL_ROOT_PASSWORD=root
     volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   db-ui:
     container_name: dbui
     image: phpmyadmin/phpmyadmin
     ports:
       - 8010:80
     environment:
       - PMA_ARBITRARY=1
       - TESTSUITE_PASSWORD=root
